### ISSUE TITLE
http://127.0.0.1:8000/college

### ISSUE THREAD

**Issue by wangzhaohe** [oddcc/django-export-csv#1]
in demo

(Xservice) swot@pp:~/app/django-export-csv-master/demo_app$ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
January 26, 2018 - 10:03:19
Django version 1.11.8, using settings 'demo_app.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Not Found: /college/
[26/Jan/2018 10:03:24] "GET /college/ HTTP/1.1" 404 2171
[26/Jan/2018 10:03:31] "GET /college HTTP/1.1" 200 3
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 127, in finish_response
    for data in self.result:
  File "/home/swot/pyenv/Xservice/local/lib/python2.7/site-packages/django_export_csv/mixin.py", line 74, in _iter_csv
    field_names = queryset_values.field_names
AttributeError: 'QuerySet' object has no attribute 'field_names'
[26/Jan/2018 10:03:31] "GET /college HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45340)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/swot/pyenv/Xservice/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 155, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 92, in run
    self.close()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 33, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------

**Comment by partounian** [comment]
Any solution to shi @wangzhaohe ?

**Comment by elementzonline** [comment]
I am also getting the same error

AttributeError: 'QuerySet' object has no attribute 'field_names'
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/dhanish/Github/HRMS_Elementz/venv/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 155, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 92, in run
    self.close()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 33, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by oddcc** [comment]
@wangzhaohe @partounian @elementzonline 
This problem is because the QuerySet object in the new version of Django no longer contains the field_names attribute.
The 0.1.3.1 release has fixed this issue, you can try it later by updating the version.

[Django document migrating-from-the-old-api](https://docs.djangoproject.com/en/1.9/ref/models/meta/#migrating-from-the-old-api)
[Django: Get list of model fields?](https://stackoverflow.com/questions/3106295/django-get-list-of-model-fields/13801711)

**Comment by elementzonline** [comment]
@oddcc Thanks for the update. I will try it.
